apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openai.secrets.name | default "openai-secrets" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openai.secrets.apiKey | b64enc }} 