apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-scheduler-service"
  labels:
    app: {{ .Release.Name }}-scheduler
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: {{ .Release.Name }}-scheduler
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Release.Name }}-scheduler-route"
spec:
  host: {{ .Values.controlPlane.components.scheduler.host | quote }}
  # ingressClassName: nginx # Not used in Route
  tls:
    termination: edge # Assuming edge termination
    # secretName: "{{ .Release.Name }}-scheduler-tls"
  to:
    kind: Service
    name: "{{ .Release.Name }}-scheduler-service"
    weight: 100
  port:
    targetPort: http # Name of the service port (targeting port 3000 on the pod)
  path: "/" # Path from the Ingress rule
