{{- if .Values.clickhouse.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup
spec:
  schedule: "0 0 * * *"  # every day at midnight
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: curlimages/curl
              command:
                - /bin/sh
                - -ec
                - |
                  BACKUP_DATE=$(date +%Y-%m-%d-%H-%M-%S)
                  echo "Creating backup..."
                  curl -X POST "http://clickhouse-0:7171/backup/create?name=$BACKUP_DATE"
                  echo "Uploading backup..."
                  curl -X POST "http://clickhouse-0:7171/backup/upload?name=$BACKUP_DATE"
                  echo "Cleaning old backups..."
                  curl -X POST "http://clickhouse-0:7171/backup/clean"
          restartPolicy: OnFailure
{{- end }} 