{{- if .Values.dataPlane.components.api.trustTestConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-trusttest-config
  labels:
    app: api
    plane: data
data:
  .trusttest_config.json: |-
    {{ .Values.dataPlane.components.api.trustTestConfig | toJson | nindent 4 }}
{{- end }} 