apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 80
      targetPort: {{ .Values.controlPlane.components.app.config.port }}
      name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Release.Name }}-app-route"
spec:
  host: {{ .Values.controlPlane.components.app.host | quote }}
  to:
    kind: Service
    name: "{{ .Release.Name }}-app-service"
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Release.Name }}-app-redirect-route"
  annotations:
    haproxy.router.openshift.io/route-redirect: https://{{ .Values.controlPlane.components.app.host }}
spec:
  host: {{ .Values.controlPlane.components.app.secondaryHost | quote }}
  to:
    kind: Service
    name: "{{ .Release.Name }}-app-service"
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
