apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-clickhouse-init
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: clickhouse-init
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running initialization scripts..."
              clickhouse-client --host $CLICKHOUSE_HOST --user $CLICKHOUSE_USER --password $CLICKHOUSE_PASSWORD -n < /init-db/init-db.sql
          env:
            - name: CLICKHOUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clickhouse-secrets
                  key: CLICKHOUSE_HOST
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clickhouse-secrets
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clickhouse-secrets
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clickhouse-secrets
                  key: CLICKHOUSE_DATABASE
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: init-db
              mountPath: /init-db
      volumes:
        - name: init-db
          configMap:
            name: {{ .Release.Name }}-clickhouse-init
            items:
              - key: init-db.sql
                path: init-db.sql 