apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clickhouse-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  CLICKHOUSE_USER: {{ .Values.clickhouse.auth.username | b64enc | quote }}
  CLICKHOUSE_DATABASE: {{ "neuraltrust" | b64enc | quote }}
  CLICKHOUSE_HOST: {{ printf "clickhouse.%s.svc.cluster.local" .Release.Namespace | b64enc | quote }}
  CLICKHOUSE_PORT: {{ "8123" | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.auth.password | b64enc | quote }} 