apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api-service"
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: api
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Release.Name }}-api-route"
spec:
  host: "{{ .Values.dataPlane.components.api.host | quote }}"
  tls:
    termination: edge
  to:
    kind: Service
    name: "{{ .Release.Name }}-api-service"
    weight: 100
  port:
    targetPort: http
  path: "/"