apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Control plane specific secrets
  secret-key: "{{ .Values.controlPlane.components.app.secrets.app.secretKey }}"
  auth-secret: {{ .Values.controlPlane.components.app.secrets.auth.secret | b64enc | quote }}
  oauth-client-key: {{ .Values.controlPlane.components.app.secrets.oauth.clientKey | b64enc | quote }}
  oauth-client-secret: {{ .Values.controlPlane.components.app.secrets.oauth.clientSecret | b64enc | quote }}
  sendgrid-api-key: {{ .Values.controlPlane.components.app.secrets.sendgrid.apiKey | b64enc | quote }}
  sendgrid-sender: {{ .Values.controlPlane.components.app.secrets.sendgrid.sender | b64enc | quote }} 
  trigger-api-key: {{ .Values.controlPlane.components.app.secrets.trigger.apiKey | b64enc | quote }}
  trigger-public-api-key: {{ .Values.controlPlane.components.app.secrets.trigger.publicApiKey | b64enc | quote }}
  