apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Control plane specific secrets
  secret-key: "{{ .Values.controlPlane.components.app.secrets.app.secretKey }}"
  auth-secret: {{ .Values.controlPlane.components.app.secrets.auth.secret | b64enc | quote }}
  oauth-client-key: {{ .Values.controlPlane.components.app.secrets.oauth.clientKey | b64enc | quote }}
  oauth-client-secret: {{ .Values.controlPlane.components.app.secrets.oauth.clientSecret | b64enc | quote }}
  resend-api-key: {{ .Values.controlPlane.components.global.resend.apiKey | b64enc | quote }}
  resend-sender: {{ .Values.controlPlane.components.global.resend.sender | b64enc | quote }} 