apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 80
      targetPort: {{ .Values.controlPlane.components.app.config.port }}
      name: http
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-app-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/x-frame-options: "DENY"
    nginx.ingress.kubernetes.io/x-content-type-options: "nosniff"
    nginx.ingress.kubernetes.io/x-xss-protection: "1; mode=block"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.controlPlane.components.app.host | quote }}
        - {{ .Values.controlPlane.components.app.secondaryHost | quote }}
      secretName: "{{ .Release.Name }}-app-tls"
  rules:
    - host: {{ .Values.controlPlane.components.app.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-app-redirect"
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "https://{{ .Values.controlPlane.components.app.host }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.controlPlane.components.app.secondaryHost | quote }}
      secretName: "{{ .Release.Name }}-app-tls"
  rules:
    - host: {{ .Values.controlPlane.components.app.secondaryHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-service
                port:
                  number: 80
