apiVersion: v2
name: neuraltrust-k8s-platform
description: A Helm chart for NeuralTrust infrastructure on Kubernetes.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Local subchart dependencies
  - name: control-plane
    version: 0.1.0
    condition: controlPlane.enabled
    repository: file://./control-plane
    tags:
      - control-plane
  - name: data-plane
    version: 0.1.0
    condition: dataPlane.enabled
    repository: file://./data-plane
    tags:
      - data-plane
