apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Control Plane JWT Secret
  CONTROL_PLANE_JWT_SECRET: {{ .Values.controlPlane.secrets.controlPlaneJWTSecret | b64enc }}
  
  # OpenAI API Key
  OPENAI_API_KEY: {{ .Values.controlPlane.secrets.openaiApiKey | b64enc }}
  
  # Resend API secrets
  resend-api-key: {{ .Values.controlPlane.secrets.resendApiKey | b64enc | quote }}
  resend-alert-sender: {{ .Values.controlPlane.secrets.resendAlertSender | b64enc | quote }}
  resend-invite-sender: {{ .Values.controlPlane.secrets.resendInviteSender | b64enc | quote }}
