apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
    plane: control
spec:
  replicas: {{ .Values.controlPlane.components.api.replicas | default 2 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
        plane: control
    spec:
      imagePullSecrets:
        {{- toYaml .Values.controlPlane.components.api.imagePullSecrets | nindent 10 }}
      containers:
      - name: {{ .Release.Name }}-api
        image: "{{ .Values.controlPlane.components.api.image.repository }}:{{ .Values.controlPlane.components.api.image.tag }}"
        imagePullPolicy: {{ .Values.controlPlane.components.api.image.pullPolicy }}
        resources:
          {{- toYaml .Values.controlPlane.components.api.resources | nindent 10 }}
        ports:
        - containerPort: 8000
        env:
        - name: DEFAULT_DATA_PLANE_URL
          value: data-plane-api-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_PASSWORD
        - name: CONTROL_PLANE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: control-plane-jwt-secret
              key: CONTROL_PLANE_JWT_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: OPENAI_API_KEY
