apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-clickhouse-init
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: clickhouse-init
          image: "{{ .Values.clickhouse.image.repository }}:{{ .Values.clickhouse.image.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running initialization scripts..."
              clickhouse-client --host $CLICKHOUSE_HOST --user $CLICKHOUSE_USER --password $CLICKHOUSE_PASSWORD -n < /init-db/init-db.sql
          env:
            - name: CLICKHOUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secrets
                  key: CLICKHOUSE_HOST
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secrets
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse
                  key: admin-password
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secrets
                  key: CLICKHOUSE_DATABASE
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
          volumeMounts:
            - name: init-db
              mountPath: /init-db
      volumes:
        - name: init-db
          configMap:
            name: {{ .Values.clickhouse.configmap.name | default "clickhouse-init-job" }}
            items:
              - key: init-db.sql
                path: init-db.sql 