apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api-service"
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: api
{{- if .Values.global.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-api-ingress"
  {{- if .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.dataPlane.components.api.host }}"
      {{- if .Values.global.ingress.tls.secretName }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
      {{- else }}
      secretName: "{{ .Release.Name }}-api-tls"
      {{- end }}
  {{- end }}
  rules:
    - host: "{{ .Values.dataPlane.components.api.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-api-service"
                port:
                  name: http
{{- end }}