apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
spec:
  selector:
    app: schemaregistry
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30092
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30443
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-svc
spec:
  selector:
    app: kafka-connect
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30099
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
spec:
  selector:
    app: kafka-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31006