apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-svc
spec:
  selector:
    app: kafka-connect
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
spec:
  selector:
    app: kafka-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
