apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataPlane.secrets.dataPlaneJWTSecretName | default (printf "%s-data-plane-jwt-secret" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-data-plane.labels" . | nindent 4 }}
type: Opaque
data:
  DATA_PLANE_JWT_SECRET: {{ .Values.dataPlane.secrets.dataPlaneJWTSecret | b64enc }}
---
{{- if .Values.dataPlane.secrets.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataPlane.secrets.openaiApiKeySecretName | default (printf "%s-openai-api-key" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-data-plane.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.dataPlane.secrets.openaiApiKey | b64enc }}
{{- end }}
---
{{- if .Values.dataPlane.secrets.googleApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataPlane.secrets.googleApiKeySecretName | default (printf "%s-google-api-key" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-data-plane.labels" . | nindent 4 }}
type: Opaque
data:
  GOOGLE_API_KEY: {{ .Values.dataPlane.secrets.googleApiKey | b64enc }}
{{- end }}
---
{{- if .Values.dataPlane.secrets.resendApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dataPlane.secrets.resendApiKeySecretName | default (printf "%s-resend-secrets" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-data-plane.labels" . | nindent 4 }}
type: Opaque
data:
  RESEND_API_KEY: {{ .Values.dataPlane.secrets.resendApiKey | b64enc }}
{{- end }} 