apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Control plane specific secrets
  resend-api-key: {{ .Values.controlPlane.components.global.resend.apiKey | b64enc | quote }}
  resend-alert-sender: {{ .Values.controlPlane.components.global.resend.alertSender | b64enc | quote }}
  resend-invite-sender: {{ .Values.controlPlane.components.global.resend.inviteSender | b64enc | quote }}
  clerk-publishable-key: {{ .Values.controlPlane.components.global.clerk.publishableKey | b64enc | quote }}
  clerk-secret-key: {{ .Values.controlPlane.components.global.clerk.secretKey | b64enc | quote }}
  clerk-webhook-secret-sessions: {{ .Values.controlPlane.components.global.clerk.webhookSecretSessions | b64enc | quote }}
  clerk-webhook-secret-users: {{ .Values.controlPlane.components.global.clerk.webhookSecretUsers | b64enc | quote }}
  clerk-authorization-callback-url: {{ .Values.controlPlane.components.global.clerk.authorizationCallbackUrl | b64enc | quote }}
  clerk-sign-in-url: {{ .Values.controlPlane.components.global.clerk.signInUrl | b64enc | quote }}
  clerk-sign-up-url: {{ .Values.controlPlane.components.global.clerk.signUpUrl | b64enc | quote }}
