apiVersion: v2
name: neuraltrust-openshift-platform
description: A Helm chart for NeuralTrust infrastructure on OpenShift.
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://static.redhat.com/libs/redhat/brand-assets/latest/corp/logo.svg

dependencies:
  # Local subchart dependencies
  - name: control-plane
    version: 0.1.0
    condition: controlPlane.enabled
    repository: file://./control-plane
    tags:
      - control-plane
  - name: data-plane
    version: 0.1.0
    condition: dataPlane.enabled
    repository: file://./data-plane
    tags:
      - data-plane
