apiVersion: v2
name: neuraltrust-openshift-platform
description: A Helm chart for NeuralTrust infrastructure on OpenShift.
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://static.redhat.com/libs/redhat/brand-assets/latest/corp/logo.svg

dependencies:
  # Local subchart dependencies
  - name: control-plane
    version: 0.1.0
    condition: controlPlane.enabled
    repository: file://./control-plane
    tags:
      - control-plane
  - name: data-plane
    version: 0.1.0
    condition: dataPlane.enabled
    repository: file://./data-plane
    tags:
      - data-plane

  # Base chart dependencies
  - name: kafka
    version: "31.0.0"
    repository: "file://../shared-charts/kafka"
    tags:
      - kafka-dependency
  - name: clickhouse
    version: "8.0.10"
    repository: "file://../shared-charts/clickhouse"
    tags:
      - clickhouse-dependency
