apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 80
      targetPort: {{ .Values.controlPlane.components.app.config.port }}
      name: http
{{- if .Values.global.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-app-ingress"
  {{- if .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.controlPlane.components.app.host | quote }}
        {{- if .Values.controlPlane.components.app.secondaryHost }}
        - {{ .Values.controlPlane.components.app.secondaryHost | quote }}
        {{- end }}
      {{- if .Values.global.ingress.tls.secretName }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
      {{- else }}
      secretName: "{{ .Release.Name }}-app-tls"
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.controlPlane.components.app.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-app-service"
                port:
                  name: http
    {{- if .Values.controlPlane.components.app.secondaryHost }}
    - host: {{ .Values.controlPlane.components.app.secondaryHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-app-service"
                port:
                  name: http
    {{- end }}
{{- end }}
