apiVersion: v2
name: neuraltrust
description: A Helm chart for NeuralTrust infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Control Plane Components
  - name: control-plane
    version: 0.1.0
    condition: controlPlane.enabled
    repository: file://control-plane
    tags:
      - control-plane

  # Data Plane Components
  - name: data-plane
    version: 0.1.0
    condition: dataPlane.enabled
    repository: file://data-plane
    tags:
      - data-plane
