global:
  postgresql:
    enabled: false
  accessMode: ReadWriteOnce
  classifierModel: "gpt"
  issuer:
    name: "letsencrypt-prod"
    server: "https://acme-v02.api.letsencrypt.org/directory"
  # Network policies
  network:
    controlPlaneCidr: "10.0.0.0/16"
    dataPlanecidr: "10.1.0.0/16"
    clientDataPlaneCidr: ""
    clientVpnCidr: ""
    excludedClientRanges: []
  ingress:
    enabled: true
    controller:
      enabled: true  # Set to false to skip installing the ingress controller
  certManager:
    enabled: true  # Set to false to skip installing cert-manager

cert-manager:
  enabled: ${global.certManager.enabled}
  email: victor.garcia@neuraltrust.ai
  issuer:
    dns01:
      enabled: false
    name: "letsencrypt-prod"
    server: "https://acme-v02.api.letsencrypt.org/directory"

clickhouse:
  enabled: true
  image:
    repository: "clickhouse/clickhouse-server"
    tag: "latest"
    pullPolicy: "Always"
    imagePullSecrets:
      - name: ""

controlPlane:
  enabled: true
  components:
    trigger:
      enabled: true
      magicLinkSecret: "${TRIGGER_MAGIC_LINK_SECRET}"
      sessionSecret: "${TRIGGER_SESSION_SECRET}"
      encryptionKey: "${TRIGGER_ENCRYPTION_KEY}"
      image:
        repository: ghcr.io/triggerdotdev/trigger.dev
        tag: latest
        pullPolicy: Always
        imagePullSecrets:
          - name: ""
      postgres:
        url: "${POSTGRES_URL}"
        user: "${POSTGRES_USER}"
        password: "${POSTGRES_PASSWORD}"
        host: "${POSTGRES_HOST}"
        database: "triggerprod"
    api:
      enabled: true
      image:
        repository: "${API_IMAGE_REPOSITORY}"
        tag: "${API_IMAGE_TAG}"
        pullPolicy: "${API_IMAGE_PULL_POLICY}"
        imagePullSecrets:
          - name: gcr-secret
      host: "${CONTROL_PLANE_API_URL}"
      secrets:
        controlPlaneJWTSecret: "${CONTROL_PLANE_JWT_SECRET}"
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
    app:
      enabled: true
      replicaCount: 1
      image:
        repository: "${WEBAPP_IMAGE_REPOSITORY}"
        tag: "${WEBAPP_IMAGE_TAG}"
        pullPolicy: "${WEBAPP_IMAGE_PULL_POLICY}"
        imagePullSecrets:
          - name: gcr-secret
      host: "${APP_URL}"
      config:
        nodeEnv: production
        port: 3000
        controlPlaneApiUrl: "${CONTROL_PLANE_API_URL}"
        dataPlaneApiUrl: "${DATA_PLANE_API_URL}"
        controlPlaneAppUrl: "${CONTROL_PLANE_APP_URL}"        
        openaiModel: "${OPENAI_MODEL}"
        nodeTlsRejectUnauthorized: "0"
      secrets:
        auth:
          secret: "${AUTH_SECRET}"
        app:
          secretKey: "${APP_SECRET_KEY}"
        oauth:
          clientKey: "${OAUTH_CLIENT_KEY}"
          clientSecret: "${OAUTH_CLIENT_SECRET}"
        sendgrid:
          apiKey: "${SENDGRID_API_KEY}"
          sender: "${SENDER}"
        trigger:
          apiKey: "${TRIGGER_API_KEY}"
          publicApiKey: "${TRIGGER_PUBLIC_API_KEY}"
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
dataPlane:
  enabled: true
  components:
    api:
      enabled: true
      image:
        repository: europe-west1-docker.pkg.dev/neuraltrust-app-prod/nt-docker/api
        tag: latest
        pullPolicy: Always
        imagePullSecrets:
          - name: gcr-secret
      host: "${CONTROL_PLANE_API_URL}"
      accessMode: ReadWriteOnce
      huggingfaceToken: "${HUGGINGFACE_TOKEN}"
      storage: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 400m
          memory: 1Gi
    kafka:
      enabled: true
      connect:
        replicas: 1
        imagePullSecrets:
          - name: ""
      broker:
        replicas: 1
        imagePullSecrets:
          - name: ""
    worker:
      enabled: true
      replicas: 1
      image:
        repository: europe-west1-docker.pkg.dev/neuraltrust-app-prod/nt-docker/workers
        tag: latest
        pullPolicy: Always
        imagePullSecrets:
          - name: gcr-secret
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 4Gi
          cpu: 1000m

postgresql:
  enabled: ${global.postgresql.enabled}
  image:
    repository: "postgres"
    tag: "15-alpine"
    pullPolicy: "IfNotPresent"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  securityContext:
    enabled: true
    fsGroup: 999
    runAsUser: 999
  service:
    type: ClusterIP
    port: 5432
  config:
    max_connections: 100
    shared_buffers: 256MB
    effective_cache_size: 768MB
    maintenance_work_mem: 64MB
    checkpoint_completion_target: 0.9
    wal_buffers: 16MB
    default_statistics_target: 100
    random_page_cost: 1.1
    effective_io_concurrency: 200
    work_mem: 2621kB
    min_wal_size: 1GB
    max_wal_size: 4GB