apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.configmap.name | default "clickhouse-init-job" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  init-db.sql: {{ .Files.Get "files/clickhouse/init-db.sql" | quote }} 