apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trigger
  labels:
    app: trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger
  template:
    metadata:
      labels:
        app: trigger
    spec:
      imagePullSecrets:
        {{- toYaml .Values.controlPlane.components.trigger.imagePullSecrets | nindent 10 }}
      containers:
      - name: trigger
        image: "{{ .Values.controlPlane.components.trigger.image.repository }}:{{ .Values.controlPlane.components.trigger.image.tag }}"
        imagePullPolicy: {{ .Values.controlPlane.components.trigger.image.pullPolicy }}
        ports:
        - containerPort: 3030
        env:
        - name: LOGIN_ORIGIN
          value: "http://trigger.{{ .Release.Namespace }}.svc.cluster.local:3030"
        - name: APP_ORIGIN
          value: "http://trigger.{{ .Release.Namespace }}.svc.cluster.local:3030"
        - name: PORT
          value: "3030"
        - name: REMIX_APP_PORT
          value: "3030"
        - name: MAGIC_LINK_SECRET
          valueFrom:
            secretKeyRef:
              name: trigger-secrets
              key: MAGIC_LINK_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: trigger-secrets
              key: SESSION_SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: trigger-secrets
              key: ENCRYPTION_KEY
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_DATABASE
          value: "trigger"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)"
        - name: DIRECT_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)"
        - name: NODE_ENV
          value: "development"
